version: '3'
services:
  webserver:
    image: akshayktg/trustgrid-network:v1
    command: bash -c 'sleep 10 && ./scripts/start_webserver.sh'
    ports:
      - "9000:8000"
    volumes:
      - ./config:/home/indy/config
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - webserver-ledger:/home/indy/ledger
    environment:
      - LOG_LEVEL=debug
      - RUST_LOG=debug
      - LEDGER_SEED=000000000000000000000000Trustee1
    networks:
      - tgrid

  node1:
    image: akshayktg/trustgrid-network:v1
    command: ./scripts/start_node.sh 1
    networks:
      - tgrid
    ports:
      - "9701-9702:9701-9702"
    volumes:
      - node1-data:/home/indy/ledger
    environment:
      - LOG_LEVEL=debug
      - RUST_LOG=debug

  node2:
    image: akshayktg/trustgrid-network:v1
    command: ./scripts/start_node.sh 2
    networks:
      - tgrid
    ports:
      - "9703-9704:9703-9704"
    volumes:
      - node2-data:/home/indy/ledger
    environment:
      - LOG_LEVEL=debug
      - RUST_LOG=debug

  node3:
    image: akshayktg/trustgrid-network:v1
    command: ./scripts/start_node.sh 3
    networks:
      - tgrid
    ports:
      - "9705-9706:9705-9706"
    volumes:
      - node3-data:/home/indy/ledger
    environment:
      - LOG_LEVEL=debug
      - RUST_LOG=debug

  node4:
    image: akshayktg/trustgrid-network:v1
    command: ./scripts/start_node.sh 4
    networks:
      - tgrid
    ports:
      - "9707-9708:9707-9708"
    volumes:
      - node4-data:/home/indy/ledger
    environment:
      - LOG_LEVEL=debug
      - RUST_LOG=debug

networks:
  tgrid:

volumes:
  webserver-cli:
  webserver-ledger:
  node1-data:
  node2-data:
  node3-data:
  node4-data:
 